---
apiVersion: v1
kind: ReplicationController
metadata:
 name: tomcat-rc
spec:
 replicas: 3
 template:
  metadata:
   name: tomcat-pod
   labels:
    author: intelliqit
    type: front-end
  spec:
   containers:
    - name: appserver
      image: tomcat
      ports:
       - containerPort: 8080
         hostPort: 7070
...
